root: true
env:
  browser: true
  node: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:astro/recommended'
  - 'plugin:svelte/recommended'
  - 'plugin:prettier/recommended'
plugins: []
rules:
  prettier/prettier: error
overrides:
  - files:
      - '*.astro'
    parser: astro-eslint-parser
    parserOptions:
      parser: '@typescript-eslint/parser'
      extraFileExtensions:
        - .astro
  - files:
      - '*.svelte'
    parser: svelte-eslint-parser
    parserOptions:
      parser: '@typescript-eslint/parser'
      extraFileExtensions:
        - .svelte
