# fly.toml app configuration file generated for opus-classical-ui on 2023-12-25T14:43:05+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "opus-classical-ui"
primary_region = "arn"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 4321
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
